package model;
// Generated Jun 5, 2012 2:41:11 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Adrate generated by hbm2java
 */
public class Adrate  implements java.io.Serializable {


     private int rateId;
     private BigDecimal currentRate;
     private BigDecimal oldRate;
     private Date dateChange;

    public Adrate() {
    }

    public Adrate(int rateId, BigDecimal currentRate, BigDecimal oldRate, Date dateChange) {
       this.rateId = rateId;
       this.currentRate = currentRate;
       this.oldRate = oldRate;
       this.dateChange = dateChange;
    }
   
    public int getRateId() {
        return this.rateId;
    }
    
    public void setRateId(int rateId) {
        this.rateId = rateId;
    }
    public BigDecimal getCurrentRate() {
        return this.currentRate;
    }
    
    public void setCurrentRate(BigDecimal currentRate) {
        this.currentRate = currentRate;
    }
    public BigDecimal getOldRate() {
        return this.oldRate;
    }
    
    public void setOldRate(BigDecimal oldRate) {
        this.oldRate = oldRate;
    }
    public Date getDateChange() {
        return this.dateChange;
    }
    
    public void setDateChange(Date dateChange) {
        this.dateChange = dateChange;
    }




}


