package model;
// Generated Oct 30, 2011 6:58:50 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Campaign generated by hbm2java
 */
public class Campaign  implements java.io.Serializable {


     private Long campaignId;
     private User user;
     private String campaignName;
     private Date startDate;
     private Date endDate;
     private BigDecimal dialyBudget;
     private String deliveryMethod;
     private String note;
     private String promoType;
     private Set<CampaignLocation> campaignLocations = new HashSet<CampaignLocation>(0);
     private Set<CampaignDemography> campaignDemographies = new HashSet<CampaignDemography>(0);
     private Set<ReportCampaign> reportCampaigns = new HashSet<ReportCampaign>(0);
     private Set<CampaignCreative> campaignCreatives = new HashSet<CampaignCreative>(0);
     private Set<CampaignOs> campaignOses = new HashSet<CampaignOs>(0);
     private Set<CampaignDevice> campaignDevices = new HashSet<CampaignDevice>(0);

    public Campaign() {
    }

	
    public Campaign(User user, String campaignName) {
        this.user = user;
        this.campaignName = campaignName;
    }
    public Campaign(User user, String campaignName, Date startDate, Date endDate, BigDecimal dialyBudget, String deliveryMethod, String note, String promoType, Set<CampaignLocation> campaignLocations, Set<CampaignDemography> campaignDemographies, Set<ReportCampaign> reportCampaigns, Set<CampaignCreative> campaignCreatives, Set<CampaignOs> campaignOses, Set<CampaignDevice> campaignDevices) {
       this.user = user;
       this.campaignName = campaignName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.dialyBudget = dialyBudget;
       this.deliveryMethod = deliveryMethod;
       this.note = note;
       this.promoType = promoType;
       this.campaignLocations = campaignLocations;
       this.campaignDemographies = campaignDemographies;
       this.reportCampaigns = reportCampaigns;
       this.campaignCreatives = campaignCreatives;
       this.campaignOses = campaignOses;
       this.campaignDevices = campaignDevices;
    }
   
    public Long getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCampaignName() {
        return this.campaignName;
    }
    
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public BigDecimal getDialyBudget() {
        return this.dialyBudget;
    }
    
    public void setDialyBudget(BigDecimal dialyBudget) {
        this.dialyBudget = dialyBudget;
    }
    public String getDeliveryMethod() {
        return this.deliveryMethod;
    }
    
    public void setDeliveryMethod(String deliveryMethod) {
        this.deliveryMethod = deliveryMethod;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getPromoType() {
        return this.promoType;
    }
    
    public void setPromoType(String promoType) {
        this.promoType = promoType;
    }
    public Set<CampaignLocation> getCampaignLocations() {
        return this.campaignLocations;
    }
    
    public void setCampaignLocations(Set<CampaignLocation> campaignLocations) {
        this.campaignLocations = campaignLocations;
    }
    public Set<CampaignDemography> getCampaignDemographies() {
        return this.campaignDemographies;
    }
    
    public void setCampaignDemographies(Set<CampaignDemography> campaignDemographies) {
        this.campaignDemographies = campaignDemographies;
    }
    public Set<ReportCampaign> getReportCampaigns() {
        return this.reportCampaigns;
    }
    
    public void setReportCampaigns(Set<ReportCampaign> reportCampaigns) {
        this.reportCampaigns = reportCampaigns;
    }
    public Set<CampaignCreative> getCampaignCreatives() {
        return this.campaignCreatives;
    }
    
    public void setCampaignCreatives(Set<CampaignCreative> campaignCreatives) {
        this.campaignCreatives = campaignCreatives;
    }
    public Set<CampaignOs> getCampaignOses() {
        return this.campaignOses;
    }
    
    public void setCampaignOses(Set<CampaignOs> campaignOses) {
        this.campaignOses = campaignOses;
    }
    public Set<CampaignDevice> getCampaignDevices() {
        return this.campaignDevices;
    }
    
    public void setCampaignDevices(Set<CampaignDevice> campaignDevices) {
        this.campaignDevices = campaignDevices;
    }




}


