package model;
// Generated Oct 17, 2011 12:07:51 PM by Hibernate Tools 3.2.1.GA



/**
 * CampaignOs generated by hbm2java
 */
public class CampaignOs  implements java.io.Serializable {


     private long campaign;
     private Campaign campaign_1;
     private String osName;

    public CampaignOs() {
    }

    public CampaignOs(long campaign, Campaign campaign_1, String osName) {
       this.campaign = campaign;
       this.campaign_1 = campaign_1;
       this.osName = osName;
    }
   
    public long getCampaign() {
        return this.campaign;
    }
    
    public void setCampaign(long campaign) {
        this.campaign = campaign;
    }
    public Campaign getCampaign_1() {
        return this.campaign_1;
    }
    
    public void setCampaign_1(Campaign campaign_1) {
        this.campaign_1 = campaign_1;
    }
    public String getOsName() {
        return this.osName;
    }
    
    public void setOsName(String osName) {
        this.osName = osName;
    }




}


