package model;
// Generated Oct 17, 2011 12:07:51 PM by Hibernate Tools 3.2.1.GA



/**
 * CampaignDevice generated by hbm2java
 */
public class CampaignDevice  implements java.io.Serializable {


     private long campaign;
     private Campaign campaign_1;
     private String deviceName;

    public CampaignDevice() {
    }

    public CampaignDevice(long campaign, Campaign campaign_1, String deviceName) {
       this.campaign = campaign;
       this.campaign_1 = campaign_1;
       this.deviceName = deviceName;
    }
   
    public long getCampaign() {
        return this.campaign;
    }
    
    public void setCampaign(long campaign) {
        this.campaign = campaign;
    }
    public Campaign getCampaign_1() {
        return this.campaign_1;
    }
    
    public void setCampaign_1(Campaign campaign_1) {
        this.campaign_1 = campaign_1;
    }
    public String getDeviceName() {
        return this.deviceName;
    }
    
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }




}


