package model;
// Generated Oct 30, 2011 5:17:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Dateex generated by hbm2java
 */
public class Dateex  implements java.io.Serializable {


     private int column1;
     private Date column2;

    public Dateex() {
    }

	
    public Dateex(int column1) {
        this.column1 = column1;
    }
    public Dateex(int column1, Date column2) {
       this.column1 = column1;
       this.column2 = column2;
    }
   
    public int getColumn1() {
        return this.column1;
    }
    
    public void setColumn1(int column1) {
        this.column1 = column1;
    }
    public Date getColumn2() {
        return this.column2;
    }
    
    public void setColumn2(Date column2) {
        this.column2 = column2;
    }




}


