package model;
// Generated 22-Oct-2011 14:04:31 by Hibernate Tools 3.2.1.GA



/**
 * Listvalue generated by hbm2java
 */
public class Listvalue  implements java.io.Serializable {


     private String column1;
     private String column2;

    public Listvalue() {
    }

    public Listvalue(String column1, String column2) {
       this.column1 = column1;
       this.column2 = column2;
    }
   
    public String getColumn1() {
        return this.column1;
    }
    
    public void setColumn1(String column1) {
        this.column1 = column1;
    }
    public String getColumn2() {
        return this.column2;
    }
    
    public void setColumn2(String column2) {
        this.column2 = column2;
    }




}


