package model;
// Generated Nov 4, 2011 1:37:20 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ReportPublish generated by hbm2java
 */
public class ReportPublish  implements java.io.Serializable {


     private Long reportrId;
     private Publish publish;
     private int totalImpressions;
     private int totalClicks;
     private BigDecimal totalCost;
     private Set<ReportrDaily> reportrDailies = new HashSet<ReportrDaily>(0);

    public ReportPublish() {
    }

	
    public ReportPublish(Publish publish, int totalImpressions, int totalClicks, BigDecimal totalCost) {
        this.publish = publish;
        this.totalImpressions = totalImpressions;
        this.totalClicks = totalClicks;
        this.totalCost = totalCost;
    }
    public ReportPublish(Publish publish, int totalImpressions, int totalClicks, BigDecimal totalCost, Set<ReportrDaily> reportrDailies) {
       this.publish = publish;
       this.totalImpressions = totalImpressions;
       this.totalClicks = totalClicks;
       this.totalCost = totalCost;
       this.reportrDailies = reportrDailies;
    }
   
    public Long getReportrId() {
        return this.reportrId;
    }
    
    public void setReportrId(Long reportrId) {
        this.reportrId = reportrId;
    }
    public Publish getPublish() {
        return this.publish;
    }
    
    public void setPublish(Publish publish) {
        this.publish = publish;
    }
    public int getTotalImpressions() {
        return this.totalImpressions;
    }
    
    public void setTotalImpressions(int totalImpressions) {
        this.totalImpressions = totalImpressions;
    }
    public int getTotalClicks() {
        return this.totalClicks;
    }
    
    public void setTotalClicks(int totalClicks) {
        this.totalClicks = totalClicks;
    }
    public BigDecimal getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(BigDecimal totalCost) {
        this.totalCost = totalCost;
    }
    public Set<ReportrDaily> getReportrDailies() {
        return this.reportrDailies;
    }
    
    public void setReportrDailies(Set<ReportrDaily> reportrDailies) {
        this.reportrDailies = reportrDailies;
    }




}


