package model;
// Generated Oct 17, 2011 12:07:51 PM by Hibernate Tools 3.2.1.GA



/**
 * TempUser generated by hbm2java
 */
public class TempUser  implements java.io.Serializable {


     private int confirmCode;
     private String emailId1;
     private String password1;
     private String userType1;
     private String userName1;

    public TempUser() {
    }

    public TempUser(int confirmCode, String emailId1, String password1, String userType1, String userName1) {
       this.confirmCode = confirmCode;
       this.emailId1 = emailId1;
       this.password1 = password1;
       this.userType1 = userType1;
       this.userName1 = userName1;
    }
   
    public int getConfirmCode() {
        return this.confirmCode;
    }
    
    public void setConfirmCode(int confirmCode) {
        this.confirmCode = confirmCode;
    }
    public String getEmailId1() {
        return this.emailId1;
    }
    
    public void setEmailId1(String emailId1) {
        this.emailId1 = emailId1;
    }
    public String getPassword1() {
        return this.password1;
    }
    
    public void setPassword1(String password1) {
        this.password1 = password1;
    }
    public String getUserType1() {
        return this.userType1;
    }
    
    public void setUserType1(String userType1) {
        this.userType1 = userType1;
    }
    public String getUserName1() {
        return this.userName1;
    }
    
    public void setUserName1(String userName1) {
        this.userName1 = userName1;
    }




}


